image: gradle:jdk17-alpine

stages:
  - test

test:
  stage: test
  script:
    - git checkout -b feature-branch
    - echo "public class FailingTest { @org.junit.Test public void test() { org.junit.Assert.fail(); } }" > mancala-java/domain/src/test/java/mancala/domain/FailingTest.java
    - gradle test

